

apiVersion: apps/v1
kind: Deployment
metadata:
  name: tp-backend
  labels: { app: tp-backend }
spec:
  replicas: 3
  selector: { matchLabels: { app: tp-backend } }
  template:
    metadata: { labels: { app: tp-backend } }
    spec:
      containers:
        - name: tp-backend
          image: tpregistry.azurecr.io/tp-backend:latest
          imagePullPolicy: Always
          ports: [ { containerPort: 8080 } ]
          envFrom:
            - secretRef: { name: tp-secrets }
---
apiVersion: v1
kind: Service
metadata:
  name: tp-backend-svc
spec:
  type: ClusterIP
  selector: { app: tp-backend }
  ports:
    - name: http
      port: 80
      targetPort: 8080
