
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tp-web
  labels: { app: tp-web }
spec:
  replicas: 3
  selector:
    matchLabels: { app: tp-web }
  template:
    metadata:
      labels: { app: tp-web }
    spec:
      containers:
        - name: tp-web
          image: tpregistry.azurecr.io/tp-web:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_API
              value: "http://tp-backend-svc"
---
apiVersion: v1
kind: Service
metadata:
  name: tp-web-svc
spec:
  type: LoadBalancer
  selector:
    app: tp-web
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
